//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erdoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PatientAppointment
    {
        public int ID { get; set; }
        [Display(Name = "First Name")]
        public string First_name { get; set; }
        [Display(Name = "Last Name")]
        public string Last_Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Specialist { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> Patientid { get; set; }
        public Nullable<System.DateTime> MorningSession { get; set; }
        public Nullable<int> Morningid { get; set; }
        public Nullable<System.DateTime> NoonSession { get; set; }
        public Nullable<int> Noonid { get; set; }
        public Nullable<System.DateTime> EveningSession { get; set; }
        public Nullable<int> Eveningid { get; set; }
        public string Note { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedByID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
